[package]
name = "rust_app"  # Replace with your project name
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "json"] }
uuid = { version = "1.3", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "8.1.1"
serde_json = "1.0"
futures = "0.3"
chrono = "0.4"