[package]
name = "rust_app"  # Replace with your project name
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1.43.0", features = ["full"] }
dotenv = "0.15"
sqlx = { version = "0.8.3", features = ["runtime-tokio-rustls", "macros", "postgres", "uuid"] }
uuid = { version = "1.3", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "9.3.0"
serde_json = "1.0.135"
futures = "0.3"
chrono = "0.4"