insert into games (title, title_style, title_color, bg_color1, bg_color2, bg_rot, abbrev_name, basic_circle_template)
values 
('The First One', 'dot open', '#ffe08b', '#f3ec78', '#af4261', 45, 'first_one', True), 
('Gotta Move Fast', 'double-circle', '#003bc6', '#047e2a', '#006eff', 125, 'gotta_move_fast', False),
('Disappearing Circles', 'dot open', '#8ff8da', '#ff4545', '#0b33fd', 145, 'disappearing_circles', True),
('Disappearing Dot', 'dot', '#8ff8da', '#64ff45', '#e90bfd', 145, 'disappearing_dot', True),
('Shrinking Circles', 'double-circle open', '#84dcff', '#b06ffa', '#4a69f7', 115, 'shrinking_circles', True),
('Moving Circles', 'triangle open', '#f7a3ff','#fff435', '#006eff', 80, 'moving_circles', True),
('Stay On The Path', "+", "#00bcd4", "#ffeb3b", "#9c27b0", 160, 'stay_on_path', True);

INSERT INTO skins (type, name, data, points) VALUES

('solid-circle', 'Black', '{"color": "black"}', 0),
('solid-circle', 'Red', '{"color": "#ff2d00"}', 50),
('solid-circle', 'Green', '{"color": "#17ff00"}', 50),
('solid-circle', 'Blue', '{"color": "#0023ff"}', 50),
('solid-circle', 'Purple', '{"color": "#e800ff"}', 50),
('solid-circle', 'Orange', '{"color": "#ff8c00"}', 50),
('solid-circle', 'White', '{"color": "white"}', 50),
('half-circle-vertical', 'Half Red Half Green 1', '{"color1": "#ff2d00", "color2": "#17ff00"}', 75),
('half-circle-horizontal', 'Half Red Half Green 2', '{"color1": "#ff2d00", "color2": "#17ff00"}', 75),
('half-circle-vertical', 'Half Red Half Blue 1', '{"color1": "#ff2d00", "color2": "#0023ff"}', 75),
('half-circle-horizontal', 'Half Red Half Blue 2', '{"color1": "#ff2d00", "color2": "#0023ff"}', 75),
('half-circle-vertical', 'Half Red Half Black 1', '{"color1": "#ff2d00", "color2": "black"}', 75),
('half-circle-horizontal', 'Half Red Half Black 2', '{"color1": "#ff2d00", "color2": "black"}', 75),
('half-circle-vertical', 'Half Red Half White 1', '{"color1": "#ff2d00", "color2": "white"}', 75),
('half-circle-horizontal', 'Half Red Half White 2', '{"color1": "#ff2d00", "color2": "white"}', 75),
('half-circle-vertical', 'Half Green Half Blue 1', '{"color1": "#17ff00", "color2": "#0023ff"}', 75),
('half-circle-horizontal', 'Half Green Half Blue 2', '{"color1": "#17ff00", "color2": "#0023ff"}', 75),
('half-circle-vertical', 'Half Green Half Purple 1', '{"color1": "#17ff00", "color2": "#e800ff"}', 75),
('half-circle-horizontal', 'Half Green Half Purple 2', '{"color1": "#17ff00", "color2": "#e800ff"}', 75),
('half-circle-vertical', 'Half Green Half Orange 1', '{"color1": "#17ff00", "color2": "#ff8c00"}', 75),
('half-circle-horizontal', 'Half Green Half Orange 2', '{"color1": "#17ff00", "color2": "#ff8c00"}', 75),
('half-circle-vertical', 'Half Green Half Black 1', '{"color1": "#17ff00", "color2": "black"}', 75),
('half-circle-horizontal', 'Half Green Half Black 2', '{"color1": "#17ff00", "color2": "black"}', 75),
('half-circle-vertical', 'Half Green Half White 1', '{"color1": "#17ff00", "color2": "white"}', 75),
('half-circle-horizontal', 'Half Green Half White 2', '{"color1": "#17ff00", "color2": "white"}', 75),
('half-circle-vertical', 'Half Blue Half Purple 1', '{"color1": "#0023ff", "color2": "#e800ff"}', 75),
('half-circle-horizontal', 'Half Blue Half Purple 2', '{"color1": "#0023ff", "color2": "#e800ff"}', 75),
('half-circle-vertical', 'Half Blue Half Orange 1', '{"color1": "#0023ff", "color2": "#ff8c00"}', 75),
('half-circle-horizontal', 'Half Blue Half Orange 2', '{"color1": "#0023ff", "color2": "#ff8c00"}', 75),
('half-circle-vertical', 'Half Blue Half Black 1', '{"color1": "#0023ff", "color2": "black"}', 75),
('half-circle-horizontal', 'Half Blue Half Black 2', '{"color1": "#0023ff", "color2": "black"}', 75),
('half-circle-vertical', 'Half Blue Half White 1', '{"color1": "#0023ff", "color2": "white"}', 75),
('half-circle-horizontal', 'Half Blue Half White 2', '{"color1": "#0023ff", "color2": "white"}', 75),
('half-circle-vertical', 'Half Purple Half Black 1', '{"color1": "#e800ff", "color2": "black"}', 75),
('half-circle-horizontal', 'Half Purple Half Black 2', '{"color1": "#e800ff", "color2": "black"}', 75),
('half-circle-vertical', 'Half Purple Half White 1', '{"color1": "#e800ff", "color2": "white"}', 75),
('half-circle-horizontal', 'Half Purple Half White 2', '{"color1": "#e800ff", "color2": "white"}', 75),
('half-circle-vertical', 'Half Orange Half Black 1', '{"color1": "#ff8c00", "color2": "black"}', 75),
('half-circle-horizontal', 'Half Orange Half Black 2', '{"color1": "#ff8c00", "color2": "black"}', 75),
('half-circle-vertical', 'Half Orange Half White 1', '{"color1": "#ff8c00", "color2": "white"}', 75),
('half-circle-horizontal', 'Half Orange Half White 2', '{"color1": "#ff8c00", "color2": "white"}', 75),
('half-circle-vertical', 'Half Black Half White 1', '{"color1": "black", "color2": "white"}', 75),
('half-circle-horizontal', 'Half Black Half White 2', '{"color1": "black", "color2": "white"}', 75);
